### ISSUE TITLE
PHP CS Fixer doesn't run automatically

### ISSUE THREAD

**Issue by giggsey** [IonBazan/composer-diff#17]
Just noticed after my MR that PHP CS Fixer has rules included, but it's not a dev dependency, nor run via GitHub Actions.

**Comment by IonBazan** [comment]
Yes, this is definitely something that needs to be fixed. Thanks for pointing it out!
The reason why the CS Fixer is not included in dev dependencies is to support wide range of PHP versions while CS Fixer v3 handles only most recent ones. We can require it globally when running under PHP 8.0 only and do the `--dry-run` check just like we do with `infection` unless you have any better ideas.

Feel free to submit a PR if you have time. Since you already contributed, your GitHub Actions will be executed without my approval. Otherwise I'll try to look into that over the weekend.

**Comment by giggsey** [comment]
Good point regarding the PHP versions. I use StyleCI for my PHP 5.3+ project, so it's not a project for me.

I'm better at GitLab CI rather than GitHub Actions, so it might be best for someone else to do it.

**Comment by IonBazan** [comment]
Solved by switching to StyleCI in 464ce36d830fba82993dbe2eecbf7975434e37c3
